overschool/chat/urls.py
from django.urls import path,include
from django.contrib.auth import views as auth_views
from . import views


app_name = 'chat'
urlpatterns = [
    path('message/create/', views.MessageViewSet.as_view()),
    path('message/all/', views.MessagesListView.as_view()),
    path('message/detail/<int:pk>', views.MessageDetailView.as_view()),

    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('main/', views.index, name='index'),
    path('main/room/<str:group_id>/', views.room, name='room'),
]

overschool/overschool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('chat.urls', 'chat'), namespace='chat')),
    # path('api/v1/chat/', include(('chat.urls', 'chat'), namespace='chat')),
]

overschool/chat/models.py
from django.db import models
from django.contrib.auth.models import User


class Groups(models.Model):
    group_name = models.TextField()

    def __str__(self):
        return self.group_name


class Members(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    group_id = models.ForeignKey(Groups, on_delete=models.CASCADE)


class Message(models.Model):
    username = models.CharField(max_length=50)
    room = models.CharField(max_length=255)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date_added',)

# class Message(models.Model):
#     user_id = models.ForeignKey(User,  on_delete=models.CASCADE)
#     group_id = models.ForeignKey(Groups, on_delete=models.CASCADE)
#     message = models.TextField()
#     date_added = models.DateTimeField(auto_now_add=True)
#
#     class Meta:
#         ordering = ('date_added',)

overschool/chat/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Message, Members

from rest_framework.permissions import IsAuthenticated, IsAdminUser
from rest_framework import generics
from .serializers import MessageSerializer
from .permissions import IsOwnerOrReadOnly


class MessageViewSet(generics.CreateAPIView):
    serializer_class = MessageSerializer


class MessagesListView(generics.ListAPIView):
    serializer_class = MessageSerializer
    queryset = Message.objects.all().order_by('room')
    permission_classes = (IsAdminUser,)


class MessageDetailView(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = MessageSerializer
    queryset = Message.objects.all().order_by('room')
    permission_classes = (IsOwnerOrReadOnly,)


@login_required
def index(request):
    auth_id = request.user.id
    members = Members.objects.filter(user_id=auth_id)
    return render(request, 'main/main.html', {'members': members})


@login_required
def room(request, group_id):
    username = request.user.username
    messages = Message.objects.filter(room=group_id)[0:25]
    return render(request, 'chat/room.html', {'room_name': group_id, 'username': username, 'messages': messages})

overschool/chat/templates/base.html
<!doctype  html>
<html  lang="en">
<head>
<link  rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"  crossorigin="anonymous">
<title>Django Authentication Example</title>
</head>
<body>
  <div  class="container">
    <div  class="row justify-content-center">
      <div  class="col-4">
      <h1  class="text-center">ItOverone</h1><br>
      {% block main %}
        <h3  class="text-center">Chat</h3>
        <a  href="{% url 'chat:logout' %}">Logout</a>
      {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

overschool/chat/templates/chat/index.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8"/>
        <title>Chatty</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
    </head>

    <body>
        <section class="section">
            <div class="container">
                <div class="columns is-multiline">
                    <div class="column is-6 is-offset-3 mb-6">
                        <section class="hero is-primary">
                            <div class="hero-body">
                                <p class="title">
                                    Chatty
                                </p>
                                <p class="subtitle">
                                    A simple chat built with Django, Channels and Redis
                                </p>
                            </div>
                        </section>
                    </div>

                    <div class="column is-4 is-offset-4">
                        <div class="field">
                            <label>Room name</label>

                            <div class="control">
                                <input class="input" type="text" placeholder="Room name" id="room-name-input">
                            </div>
                        </div>

                        <div class="field">
                            <label>Username</label>

                            <div class="control">
                                <input class="input" type="text" placeholder="Username" id="username-input">
                            </div>
                        </div>

                        <div class="field">
                            <div class="control">
                                <a class="button is-info" id="room-name-submit">Submit</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <script>
            document.querySelector('#room-name-input').focus();

            document.querySelector('#room-name-submit').onclick = function(e) {
                var roomName = document.querySelector('#room-name-input').value;
                var userName = document.querySelector('#username-input').value;

                window.location.replace(roomName + '/?username=' + userName);
            };
        </script>
    </body>
</html>

overschool/chat/templates/chat/room.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8"/>
        <title>Chat</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css">
    </head>

    <body>
    <a href="{% url 'chat:logout' %}" class="button is-danger" style="float: right">Logout</a>

        <section class="section">
            <div class="container">
                <div class="columns is-multiline">
                    <div class="column is-6 is-offset-3 mb-6">
                        <section class="hero is-primary">
                            <div class="hero-body">
                                <p class="title">
                                    Chat
                                </p>
                                <p class="subtitle">
                                    chat built with Django, Channels and Redis
                                </p>
                            </div>
                        </section>
                    </div>

                    <div class="column is-6 is-offset-3">
                        <div class="box">
                            <div id="chat-messages" style="max-height: 300px; overflow-y: scroll;">{% for m in messages %}<b>{{ m.username }}</b>: {{ m.content }}<br>{% endfor %}</div>
                        </div>

                        <div class="field">
                            <div class="control">
                                <input class="input" type="text" placeholder="Message" id="chat-message-input">
                            </div>
                        </div>

                        <div class="field">
                            <div class="control">
                                <a class="button is-info" id="chat-message-submit">Submit</a>
                            </div>
                        </div>

                        <small class="has-text-grey-light">Your username: {{ username }}</small>
                    </div>
                </div>
            </div>
        </section>

       {{ room_name|json_script:"json-roomname" }}
       {{ username|json_script:"json-username" }}

        <script>
            function scrollToBottom() {
                let objDiv = document.getElementById("chat-messages");
                objDiv.scrollTop = objDiv.scrollHeight;
            }

            scrollToBottom();

            const roomName = JSON.parse(document.getElementById('json-roomname').textContent);
            const userName = JSON.parse(document.getElementById('json-username').textContent);

            const chatSocket = new WebSocket(
                'ws://'
                + window.location.host
                + '/ws/'
                + roomName
                + '/'
            );

            chatSocket.onmessage = function(e) {
                console.log('onmessage');

                const data = JSON.parse(e.data);

                if (data.message) {
                    document.querySelector('#chat-messages').innerHTML += ('<b>' + data.username + '</b>: ' + data.message + '<br>');
                } else {
                    alert('The message is empty!');
                }

                scrollToBottom();
            };

            chatSocket.onclose = function(e) {
                console.log('The socket close unexpectadly');
            };

            document.querySelector('#chat-message-submit').onclick = function(e) {
                const messageInputDom = document.querySelector('#chat-message-input');
                const message = messageInputDom.value;

                chatSocket.send(JSON.stringify({
                    'message': message,
                    'username': userName,
                    'room': roomName
                }));

                messageInputDom.value = '';
            };
        </script>
    </body>
</html>

overschool/chat/templates/main/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main</title>
</head>
<body>
    <div>{% for m in members %}
        <br><a  href="{% url 'chat:room' m.group_id.pk %}">
            <button type="submit" class="btn btn-primary btn-block">{{ m.group_id }}</button>
        </a><br><br><br>
        {% endfor %}
    </div>

</body>
</html>